# Generated by Django 5.2 on 2025-05-08 20:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('categoria', models.CharField(choices=[('corrente', 'Conta Corrente'), ('pagamento', 'Conta de Pagamento'), ('carteira', 'Carteira'), ('poupanca', 'Poupança'), ('investimento', 'Investimento')], default='corrente', max_length=20, verbose_name='Tipo de Conta')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Conta Ativa?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data_vencimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vencimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('efetivada', models.BooleanField(default=False, verbose_name='Efetivada?')),
                ('recorrente', models.CharField(choices=[('fixa', 'Fixa Mensal'), ('variavel', 'Variável'), ('unica', 'Única')], default='unica', max_length=20, verbose_name='Recorrência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('categoria', models.CharField(choices=[('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('vestuario', 'Vestuário'), ('servicos', 'Serviços'), ('impostos', 'Impostos'), ('pets', 'Pets'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('parcela_atual', models.PositiveIntegerField(default=1, verbose_name='Parcela Atual')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='gestao.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('data_vencimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vencimento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('efetivada', models.BooleanField(default=False, verbose_name='Efetivada?')),
                ('recorrente', models.CharField(choices=[('fixa', 'Fixa Mensal'), ('variavel', 'Variável'), ('unica', 'Única')], default='unica', max_length=20, verbose_name='Recorrência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('categoria', models.CharField(choices=[('salario', 'Salário'), ('freelance', 'Freelance'), ('investimentos', 'Investimentos'), ('comissao', 'Comissão'), ('vendas', 'Vendas'), ('presente', 'Presente'), ('beneficios', 'Benefícios'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('origem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Origem/Fonte')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='gestao.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
