# Generated by Django 5.2 on 2025-05-09 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='gestao.conta'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='gestao.conta'),
        ),
    ]
