# Generated by Django 5.2.4 on 2025-08-04 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_despesa_conta_alter_receita_conta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='id_externo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Externo da API'),
        ),
        migrations.CreateModel(
            name='ConexaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banco', models.CharField(max_length=100)),
                ('token_acesso', models.CharField(max_length=255)),
                ('id_conexao_api', models.CharField(max_length=255, unique=True)),
                ('data_conexao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conexão Bancária',
                'verbose_name_plural': 'Conexões Bancárias',
                'ordering': ['-data_conexao'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('origem_api', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria_api', models.CharField(blank=True, max_length=100, null=True)),
                ('id_api', models.CharField(max_length=255, unique=True)),
                ('importada', models.BooleanField(default=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transação Importada',
                'verbose_name_plural': 'Transações Importadas',
                'ordering': ['-data'],
            },
        ),
    ]
